# Generated by Django 4.1.7 on 2023-02-19 20:00

import browse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название цели')),
                ('description', models.TextField(verbose_name='Подробности')),
                ('owner', models.TextField(verbose_name='Ответственный')),
                ('block', models.CharField(choices=[('Подбор', 'Подбор'), ('Адаптация', 'Адаптация'), ('Развитие персонала', 'Развитие персонала'), ('HR-сопровождение', 'HR-сопровождение'), ('Корп. культура и бенефиты', 'Корп. культура и бенефиты'), ('Кадровый учет и з/п', 'Кадровый учет и з/п'), ('HR-бренд внешний', 'HR-бренд внешний'), ('Внутренняя работа отдела', 'Внутренняя работа отдела'), ('Оценка', 'Оценка')], max_length=30, verbose_name='Блок')),
                ('planned', models.BooleanField(verbose_name='Запланированная')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Квартал')),
                ('weight', models.FloatField()),
                ('current', models.BooleanField(verbose_name='Утверждённая')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
