# Generated by Django 4.1.7 on 2023-02-19 20:02

import browse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
