# Generated by Django 4.1.7 on 2023-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_goal_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='owner_id',
            field=models.IntegerField(verbose_name='ID Ответственного'),
        ),
    ]
