# Generated by Django 4.1.7 on 2023-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_alter_goal_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='chat',
            field=models.JSONField(null=True, verbose_name='Чат'),
        ),
    ]
