# Generated by Django 4.1.7 on 2023-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_goal_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='history',
            field=models.JSONField(null=True, verbose_name='История'),
        ),
    ]
