# Generated by Django 4.1.7 on 2023-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_goal_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current',
        ),
        migrations.AddField(
            model_name='goal',
            name='current_level',
            field=models.IntegerField(null=True, verbose_name='Утверждённая'),
        ),
    ]
