# Generated by Django 4.1.7 on 2023-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0010_alter_goal_fact_mark_alter_goal_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_level',
        ),
        migrations.AddField(
            model_name='goal',
            name='current',
            field=models.PositiveSmallIntegerField(choices=[('Да', True), ('Нет', False)], null=True, verbose_name='Запланированная'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='planned',
            field=models.PositiveSmallIntegerField(choices=[('Да', True), ('Нет', False)], null=True, verbose_name='Запланированная'),
        ),
    ]
