# Generated by Django 4.1.7 on 2023-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0012_alter_goal_current_alter_goal_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Утверждённая'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='planned',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Запланированная'),
        ),
    ]
