# Generated by Django 4.1.7 on 2023-03-24 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0014_alter_goal_fact_mark_alter_goal_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
