# Generated by Django 4.1.7 on 2023-03-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0017_chat_owner_id_history_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='field',
        ),
        migrations.RemoveField(
            model_name='history',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='history',
            name='old_data',
        ),
        migrations.CreateModel(
            name='FieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(verbose_name='Поле')),
                ('old_data', models.TextField(verbose_name='Было')),
                ('new_data', models.TextField(verbose_name='Стало')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.history')),
            ],
            options={
                'verbose_name': 'Поле (история)',
                'verbose_name_plural': 'Поля (история)',
            },
        ),
    ]
