# Generated by Django 4.1.7 on 2023-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0018_remove_history_field_remove_history_new_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=25, verbose_name='Квартал')),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.CharField(choices=[], max_length=25, verbose_name='Квартал'),
        ),
    ]
