# Generated by Django 4.1.7 on 2023-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0021_alter_goal_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='isdone',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Выполнена'),
            preserve_default=False,
        ),
    ]
