# Generated by Django 4.1.7 on 2023-04-29 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0024_alter_goal_fact_mark_alter_goal_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
