# Generated by Django 4.1.7 on 2023-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0025_alter_chat_created_at_alter_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
