# Generated by Django 4.1.7 on 2023-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0026_alter_chat_created_at_alter_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='block',
            field=models.CharField(choices=[('', ''), ('Подбор', 'Подбор'), ('Адаптация', 'Адаптация'), ('Развитие персонала', 'Развитие персонала'), ('HR-сопровождение', 'HR-сопровождение'), ('Корп. культура и бенефиты', 'Корп. культура и бенефиты'), ('Кадровый учет и з/п', 'Кадровый учет и з/п'), ('HR-бренд внешний', 'HR-бренд внешний'), ('Внутренняя работа отдела', 'Внутренняя работа отдела'), ('Оценка', 'Оценка')], max_length=30, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current',
            field=models.BooleanField(choices=[('', ''), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Утверждённая'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='isdone',
            field=models.BooleanField(choices=[('', ''), (True, 'Да'), (False, 'Нет')], verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='planned',
            field=models.BooleanField(choices=[('', ''), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Запланированная'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.CharField(choices=[('', ''), ('2 квартал 2023', '2 квартал 2023'), ('3 квартал 2023', '3 квартал 2023'), ('4 квартал 2023', '4 квартал 2023'), ('1 квартал 2024', '1 квартал 2024'), ('2 квартал 2024', '2 квартал 2024'), ('3 квартал 2024', '3 квартал 2024')], max_length=25, verbose_name='Квартал'),
        ),
    ]
