# Generated by Django 4.1.7 on 2023-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0028_alter_goal_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.CharField(choices=[('', ''), ('2 квартал 2023', '2 квартал 2023'), ('3 квартал 2023', '3 квартал 2023'), ('4 квартал 2023', '4 квартал 2023'), ('1 квартал 2024', '1 квартал 2024'), ('2 квартал 2024', '2 квартал 2024'), ('3 квартал 2024', '3 квартал 2024')], max_length=25, verbose_name='Квартал'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(verbose_name='План')),
                ('fact', models.TextField(verbose_name='Факт')),
                ('block', models.CharField(choices=[('', ''), ('Подбор', 'Подбор'), ('Адаптация', 'Адаптация'), ('Развитие персонала', 'Развитие персонала'), ('HR-сопровождение', 'HR-сопровождение'), ('Корп. культура и бенефиты', 'Корп. культура и бенефиты'), ('Кадровый учет и з/п', 'Кадровый учет и з/п'), ('HR-бренд внешний', 'HR-бренд внешний'), ('Внутренняя работа отдела', 'Внутренняя работа отдела'), ('Оценка', 'Оценка')], max_length=30, verbose_name='Блок')),
                ('quarter', models.CharField(choices=[('', ''), ('2 квартал 2023', '2 квартал 2023'), ('3 квартал 2023', '3 квартал 2023'), ('4 квартал 2023', '4 квартал 2023'), ('1 квартал 2024', '1 квартал 2024'), ('2 квартал 2024', '2 квартал 2024'), ('3 квартал 2024', '3 квартал 2024')], max_length=25, verbose_name='Квартал')),
                ('goals', models.ManyToManyField(to='browse.goal')),
            ],
            options={
                'verbose_name': 'Сводка',
                'verbose_name_plural': 'Сводки',
            },
        ),
    ]
