# Generated by Django 4.1.7 on 2023-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0031_summary_average_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='fact',
            field=models.TextField(default='', null=True, verbose_name='Факт'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='plan',
            field=models.TextField(default='', null=True, verbose_name='План'),
        ),
    ]
