# Generated by Django 4.1.7 on 2023-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0032_alter_summary_fact_alter_summary_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='block',
            field=models.CharField(choices=[('', ''), ('Подбор', 'Подбор'), ('Адаптация', 'Адаптация'), ('Развитие персонала', 'Развитие персонала'), ('HR-сопровождение', 'HR-сопровождение'), ('Корп. культура и бенефиты', 'Корп. культура и бенефиты'), ('Кадровый учет и зп', 'Кадровый учет и зп'), ('HR-бренд внешний', 'HR-бренд внешний'), ('Внутренняя работа отдела', 'Внутренняя работа отдела'), ('Оценка', 'Оценка')], max_length=30, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.CharField(max_length=25, verbose_name='Квартал'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='block',
            field=models.CharField(choices=[('', ''), ('Подбор', 'Подбор'), ('Адаптация', 'Адаптация'), ('Развитие персонала', 'Развитие персонала'), ('HR-сопровождение', 'HR-сопровождение'), ('Корп. культура и бенефиты', 'Корп. культура и бенефиты'), ('Кадровый учет и зп', 'Кадровый учет и зп'), ('HR-бренд внешний', 'HR-бренд внешний'), ('Внутренняя работа отдела', 'Внутренняя работа отдела'), ('Оценка', 'Оценка')], max_length=30, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='quarter',
            field=models.CharField(max_length=25, verbose_name='Квартал'),
        ),
    ]
