# Generated by Django 4.1.7 on 2023-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.CharField(default='', max_length=30, verbose_name='Комментарий'),
        ),
    ]
