# Generated by Django 4.1.7 on 2023-04-06 12:00

from django.db import migrations, models
import django_cropper_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_notification_options_notification_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_cropper_image.fields.ImageCropperField(max_length=255, upload_to='image')),
            ],
        ),
    ]
