# Generated by Django 4.1.7 on 2023-04-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0026_alter_chat_created_at_alter_history_created_at'),
        ('users', '0002_alter_notification_options_notification_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='goal',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='browse.goal'),
            preserve_default=False,
        ),
    ]
