# Generated by Django 4.1.7 on 2023-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='field',
            field=models.TextField(null=True, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_goal',
            field=models.BooleanField(default=False, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_data',
            field=models.TextField(null=True, verbose_name='Стало'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='old_data',
            field=models.TextField(null=True, verbose_name='Было'),
        ),
    ]
