# Generated by Django 4.1.7 on 2023-04-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0026_alter_chat_created_at_alter_history_created_at'),
        ('users', '0004_alter_notification_field_alter_notification_is_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='field',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='old_data',
        ),
        migrations.AddField(
            model_name='notification',
            name='field_change',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='browse.fieldchange'),
            preserve_default=False,
        ),
    ]
