# Generated by Django 4.1.7 on 2023-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_notification_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/static/users/img/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватарки',
            },
        ),
    ]
