# Generated by Django 4.1.7 on 2023-05-08 16:39

from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_image_user_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.Image.wrapper, validators=[users.validators.validate_image_extension, users.validators.file_size], verbose_name='Аватар'),
        ),
    ]
