# Generated by Django 4.1.5 on 2023-05-09 13:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.Image.wrapper, verbose_name='Аватар'),
        ),
    ]
